dist: artful
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7-arm-linux-gnueabihf
      - gcc-7-arm-linux-gnueabihf

before_install:
  - pip install --user cpp-coveralls

script:
  - ./build_debug.sh
  - ./build.sh

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
