dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-arm-linux-gnueabihf

before_install:
  - pip install --user cpp-coveralls

script:
  - ./build_debug
  - rm -rf build
  - ./build

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
