dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-arm-linux-gnueabihf
      - clang-5.0

before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/arm-linux-gnueabihf-g++ CC=/usr/bin/arm-linux-gnueabihf-gcc cmake -DCMAKE_TOOLCHAIN_FILE=./linux/arm-linux-gnueabihf.cmake -DCOVERAGE=1 .
  - cmake --build linux/
  - linux/tests

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
