dist: trusty
sudo: false
language: cpp

addons:
  apt:
    packages:
      - g++-arm-linux-gnueabihf
      - gcc-arm-linux-gnueabihf

before_install:
  - sudo apt-get install g++-arm-linux-gnueabihf
  - pip install --user cpp-coveralls

script:
  - ./build_debug.sh
  - ./build.sh

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
