dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-arm-linux-gnueabihf

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir linux/build && cd linux/build
  - cmake -DCOVERAGE=1 ../
  - cmake --build ../ -DCMAKE_TOOLCHAIN_FILE=../arm-linux-gnueabihf.cmake

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 
